name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH to Hostinger and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no root@69.62.79.109<< 'EOF'
            cd /var/www/PATH_LAB_MVP
            git pull origin main
            # Rebuild the frontend
            cd client && npm install && npm run build
            # Rebuild the backend
            cd ../server && npm install && npm run build
            # Restart the app (if using pm2 or other process manager)
            pm2 restart all
          EOF
